---
# Some providers (e.g. Amazon EC2) assign internal 172.x.x.x IP
# addresses to their virtual machines. It's important to use the real
# public IP in the instructions brasscrow generates, because the
# internal addresses are not publicly accessible.
#
# Some providers (e.g. Amazon EC2 and Linode) do not use the name that
# is provided in the API call as the server's hostname. It's important
# to use the friendly name in the instructions rather than an ugly,
# randomly generated hostname.
#
# Each 'genesis' role for the providers that brasscrow natively supports
# sets the brasscrow_ipv4_address and brasscrow_server_name variables in
# an attempt to correct the limitations laid out above. However, it is
# also necessary to fall back to default sane values if users choose to
# run brasscrow on their own servers or against other cloud providers.
#
# These conditionals are here for that very reason :)

- name: Set the brasscrow_ipv4_address variable to the value provided by a 'genesis' role if one is defined
  set_fact:
    brasscrow_ipv4_address: "{{ hostvars['127.0.0.1']['brasscrow_ipv4_address'] }}"
  when: hostvars['127.0.0.1']['brasscrow_ipv4_address'] is defined

- name: Set the brasscrow_ipv4_address variable to the default value if it doesn't already have one. The default is the value defined in the inventory file, which should be the IP address of the server that is being configured.
  set_fact:
    brasscrow_ipv4_address: "{{ inventory_hostname }}"
  when: brasscrow_ipv4_address is not defined

- name: Set the brasscrow_server_name variable to the value provided by a 'genesis' role if one is defined
  set_fact:
    brasscrow_server_name: "{{ hostvars['127.0.0.1']['brasscrow_server_name'] }}"
  when: hostvars['127.0.0.1']['brasscrow_server_name'] is defined

- name: Set the brasscrow_server_name variable to the default value if it doesn't already have one. The default is the value of the hostname retrieved from the server that is being configured.
  set_fact:
    brasscrow_server_name: "{{ ansible_hostname }}"
  when: brasscrow_server_name is not defined
