- name: Prepare the new server for Ansible
# =========================================
  hosts: brasscrow-host
  gather_facts: no

  remote_user: root
  become: true

  tasks:
    - name: Install Python using a raw SSH command to enable the execution of Ansible modules
      raw: apt update && apt install python -y
      args:
        executable: /bin/bash


- name: Configure the Server and install required software
# ========================================================
  hosts: brasscrow-host

  remote_user: root
  become: true

  roles:
    - common
    # OpenConnect must be set up before L2TP/IPsec in order to avoid
    # issues.
    - openconnect
    - l2tp-ipsec
    - openvpn
    - stunnel
    - shadowsocks
    - ssh
    - tinyproxy
    - tor-bridge
    - sslh
    - monit
    - ufw
    - wireguard
    - brasscrow-mirror
    - brasscrow-gateway
