#!/bin/bash
#start / stop wireguard

DATE=`date +%Y-%m-%d:%H:%M:%S`
MYIP=`dig +short myip.opendns.com @resolver1.opendns.com`

case "$1" in
    start) 
    echo 'starting vpn connection to jamesdimple' 
    sudo wg-quick up wg0-client
    ;;
    stop) 
    echo 'stopping vpn connection to jamesdimple' 
    sudo wg-quick down wg0-client
    ;;
    status)
    if ! ifconfig wg0-client | grep -q "00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00"
    then
       echo $DATE vpn is down
       echo your public ip is $MYIP
       exit 0
    else
       echo $DATE vpn is up
       echo your public ip is $MYIP
    fi
    ;;
    *) 
    echo 'Must use start/stop' 
    exit 1
    ;;
esac

#sudo wg-quick $1 wg0-client
