---
#Add dns record to cloudflare

- cloudflare_dns:
    zone: {{ brasscrow_dnszone }}
    record: {{ brasscrow_dnsname }}
    type: A
    value: {{ brasscrow_ipv4_address }}
    account_email: {{ cloudflare_email }}
    account_api_token: {{ cloudflare_token }}
  register: record